import type { PropertyDef, VisibleWhenCondition } from './properties'

// --- Port Types ---

export type PortType = 'geometry' | 'material' | 'mesh' | 'light' | 'camera' | 'scene' | 'float' | 'vec3' | 'color' | 'texture' | 'path' | 'sfloat' | 'svec2' | 'svec3'

export interface PortDef {
  name: string
  type: PortType
  label?: string
  visibleWhen?: VisibleWhenCondition | VisibleWhenCondition[]
}

// --- Node Definition (static blueprint) ---

export interface NodeDefinition {
  type: string
  label: string
  category: 'geometry' | 'material' | 'object' | 'transform' | 'light' | 'camera' | 'shader' | 'math' | 'color' | 'texture' | 'time' | 'input' | 'effect' | 'scene' | 'path'
  inputs: PortDef[]
  outputs: PortDef[]
  properties: PropertyDef[]
  defaults: Record<string, unknown>
  /** Internal nodes are not shown in the node palette (e.g. auto-generated by Expand to Graph) */
  hidden?: boolean
}

// --- Graph Node (instance in the graph) ---

export interface GraphNode {
  id: string
  type: string // references NodeDefinition.type
  position: { x: number; y: number }
  data: Record<string, unknown> // property values
}

// --- Graph Edge ---

export interface GraphEdge {
  id: string
  source: string      // source node id
  sourceHandle: string // output port name
  target: string      // target node id
  targetHandle: string // input port name
}

// --- Compiled Scene (output of compiler) ---

export interface CompiledTransform {
  position: [number, number, number]
  rotation: [number, number, number]  // radians
  scale: [number, number, number]
}

export interface CompiledMesh {
  id: string
  geometryNodeId: string       // source geometry node
  geometryType: string
  geometryProps: Record<string, unknown>
  /** Set when geometryType === 'gltf-mesh' — points to the source file + mesh index */
  geometrySource?: { type: 'gltf'; dataUrl: string; meshIndex: number; matrixWorld?: number[]; extraFiles?: { name: string; dataUrl: string }[] }
  materialNodeId: string       // source material node
  materialType: string
  materialProps: Record<string, unknown>
  /** Set when materialType === 'shader/output' or material node has shaderGraph port connected */
  shaderGraph?: {
    fragmentShader: string
    vertexShader?: string       // full custom vertex shader (unlit mode: shader/output → mesh)
    vertexPreamble?: string     // PBR mode: prepend to Three.js vertex shader
    vertexBodyForPBR?: string   // PBR mode: inject after #include <displacementmap_vertex>
    /** true = PBR mode (shader/output → material → mesh): uses MeshStandardMaterial + onBeforeCompile */
    pbrMode?: boolean
    uniforms: Record<string, { value: number | [number, number] | [number, number, number] }>
    uniformNodeMap: Record<string, string>
    bridgeUniforms: Record<string, string>
  }
  transformNodeIds: string[]   // node IDs in the transform chain
  transform: CompiledTransform
}

export interface CompiledLight {
  id: string
  lightType: string  // 'ambient' | 'directional' | 'point'
  props: Record<string, unknown>
  targetNodeId?: string  // directional light target mesh node id
  pathNodeId?: string
  pathProgress?: number
}

export interface CompiledCamera {
  nodeId: string
  position: [number, number, number]
  rotation: [number, number, number]  // degrees
  fov: number
  mode: number  // 0 = Free, 1 = Target, 2 = Path
  targetNodeId?: string
  pathNodeId?: string
  pathProgress?: number
  pathLookAhead?: boolean
}

export interface CompiledPath {
  id: string
  pathType: 'line' | 'circle' | 'arc'
  pathProps: Record<string, unknown>
  position: [number, number, number]
  transformNodeIds: string[]  // Transform nodes downstream from this path (in order)
}

export interface CompiledGLTF {
  id: string
  fileDataUrl?: string
  fileName?: string
  /** Associated files for multi-file .gltf (bin, textures) — mapped by filename */
  extraFiles?: { name: string; dataUrl: string }[]
  /** 0=Off, 1=BBox-Mitte, 2=BBox-Boden, 3=Manuell */
  centerMode: number
  originX: number
  originY: number
  originZ: number
  transform: CompiledTransform
  transformNodeIds: string[]
}

export interface CompiledBackgroundShader {
  materialNodeId: string
  materialProps: Record<string, unknown>
  /** Set when connected node is shader/output (visual shader graph) */
  generatedFragmentShader?: string
  generatedUniforms?: Record<string, { value: number | [number, number] | [number, number, number] }>
  uniformNodeMap?: Record<string, string>
  /** Bridge: uniformKey → "sourceNodeId:sourceHandle" for CPU float nodes wired into shader inputs */
  bridgeUniforms?: Record<string, string>
}

export interface CompiledScene {
  meshes: CompiledMesh[]
  gltfObjects: CompiledGLTF[]
  paths: CompiledPath[]
  lights: CompiledLight[]
  camera?: CompiledCamera
  backgroundShader?: CompiledBackgroundShader
  smoothShading: boolean
  bgColor: string
  envMapDataUrl?: string
  envIntensity: number
  showEnvBackground: boolean
}
