import type { ShaderPreset } from '../engine/types'
import fragmentShader from '../shaders/presets/mesh-gradient.frag'

export const meshGradientPreset: ShaderPreset = {
  id: 'mesh-gradient',
  name: 'Mesh Gradient',
  description: 'iOS/Figma-style mesh gradient with smooth color blending in Oklab space',
  category: 'gradient',
  fragmentShader,
  parameters: [
    {
      type: 'color',
      uniform: 'u_color1',
      label: 'Color 1',
      group: 'Colors',
      default: [0.34, 0.34, 1.0],
    },
    {
      type: 'color',
      uniform: 'u_color2',
      label: 'Color 2',
      group: 'Colors',
      default: [1.0, 0.4, 0.7],
    },
    {
      type: 'color',
      uniform: 'u_color3',
      label: 'Color 3',
      group: 'Colors',
      default: [0.2, 0.8, 0.9],
    },
    {
      type: 'color',
      uniform: 'u_color4',
      label: 'Color 4',
      group: 'Colors',
      default: [0.9, 0.6, 0.2],
    },
    {
      type: 'float',
      uniform: 'u_speed',
      label: 'Speed',
      group: 'Animation',
      min: 0,
      max: 3,
      step: 0.01,
      default: 1.0,
    },
    {
      type: 'float',
      uniform: 'u_complexity',
      label: 'Complexity',
      group: 'Shape',
      min: 0.5,
      max: 5,
      step: 0.1,
      default: 2.0,
    },
    {
      type: 'float',
      uniform: 'u_distortion',
      label: 'Distortion',
      group: 'Shape',
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.5,
    },
    {
      type: 'float',
      uniform: 'u_softness',
      label: 'Softness',
      group: 'Shape',
      min: 0,
      max: 2,
      step: 0.01,
      default: 1.0,
    },
    {
      type: 'float',
      uniform: 'u_grain',
      label: 'Grain',
      group: 'Effects',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.2,
    },
  ],
}
